import json
from openai import OpenAI
from .tools import tools
from utils import find_user_by_email, get_cpu_usage, get_memory_usage


model_version = "gpt-5"

def run(msg=None):
    if msg is None:
        return "No message provided"

    openAI_client = OpenAI()

    # =========================
    # Step 1: Ask
    # =========================
    input_list = [{"role": "user", "content": msg}]

    # 2. Prompt the model with tools defined
    response = openAI_client.responses.create(
        model=model_version,
        tools=tools,
        input=input_list,
    )
    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "find_user_by_email":
                args_dict = json.loads(item.arguments)
                email = args_dict.get("email")

                result = find_user_by_email(email)

                # 4. Provide function call results to the model
                input_list.append(
                    {
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": json.dumps({"user_detail": result}),
                    }
                )

                response = openAI_client.responses.create(
                    model=model_version,
                    # Use this when U want to use result from tool only
                    # instructions="Respond only with a CPU usage generated by a tool naturally.",
                    instructions="Based on the tool's output, inform the user about the current user detail in a complete, natural sentence. For example: 'The current user detail is [value]%.",
                    tools=tools,
                    input=input_list,
                )
            if item.name == "get_cpu_usage":
                result = get_cpu_usage()

                # 4. Provide function call results to the model
                input_list.append(
                    {
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": json.dumps({"cpu_usage": result}),
                    }
                )

                response = openAI_client.responses.create(
                    model=model_version,
                    # Use this when U want to use result from tool only
                    # instructions="Respond only with a CPU usage generated by a tool naturally.",
                    instructions="Based on the tool's output, inform the user about the current CPU usage in a complete, natural sentence. For example: 'The current CPU usage is [value]%.",
                    tools=tools,
                    input=input_list,
                )

            if item.name == "get_memory_usage":
                result = get_memory_usage()

                # 4. Provide function call results to the model
                input_list.append(
                    {
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": json.dumps({"memory_usage": result}),
                    }
                )

                response = openAI_client.responses.create(
                    model=model_version,
                    # Use this when U want to use result from tool only
                    # instructions="Respond only with a Memory usage generated by a tool naturally.",
                    instructions="Based on the tool's output, inform the user about the current Memory usage in a complete, natural sentence. For example: 'The current Memory usage is [value]%.",
                    tools=tools,
                    input=input_list,
                )

    return response
